
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: "2023-10-21T07:49:04Z"
  generation: 1
  labels:
    operators.coreos.com/aqua-operator-certified.openshift-gitops: ""
  name: aqua-operator-certified
  namespace: openshift-gitops
  resourceVersion: "687837"
  uid: 8698e007-0eba-45df-97b8-599f4908c37a
spec:
  channel: "2022.4"
  installPlanApproval: Automatic
  name: aqua-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: aqua-operator.2022.4.348
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operators.coreos.com/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"name":"crunchy-postgres-operator","namespace":"openshift-operators"},"spec":{"channel":"v5","name":"crunchy-postgres-operator","source":"certified-operators","sourceNamespace":"openshift-marketplace"}}
  creationTimestamp: "2023-10-20T20:22:27Z"
  generation: 1
  labels:
    operators.coreos.com/crunchy-postgres-operator.openshift-operators: ""
  name: crunchy-postgres-operator
  namespace: openshift-operators
  resourceVersion: "935267"
  uid: 6fba2e0f-2cb3-4312-bb43-7d322924c94a
spec:
  channel: v5
  name: crunchy-postgres-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: "2023-10-22T06:05:02Z"
  generation: 1
  labels:
    operators.coreos.com/devspaces.openshift-operators: ""
  name: devspaces
  namespace: openshift-operators
  resourceVersion: "935284"
  uid: d7a2d267-1f1b-4097-8382-3f444676eded
spec:
  channel: stable
  installPlanApproval: Automatic
  name: devspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: devspacesoperator.v3.9.0
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    olm.generated-by: install-c8j8s
  creationTimestamp: "2023-10-22T06:10:45Z"
  generation: 1
  labels:
    operators.coreos.com/devworkspace-operator.openshift-operators: ""
  name: devworkspace-operator-fast-redhat-operators-openshift-marketplace
  namespace: openshift-operators
  resourceVersion: "935301"
  uid: 8fd2761e-577a-431f-9443-dd04d4186036
spec:
  channel: fast
  installPlanApproval: Automatic
  name: devworkspace-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: devworkspace-operator.v0.23.0
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operators.coreos.com/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"name":"openshift-gitops","namespace":"openshift-operators"},"spec":{"channel":"latest","name":"openshift-gitops-operator","source":"redhat-operators","sourceNamespace":"openshift-marketplace"}}
  creationTimestamp: "2023-10-20T20:22:27Z"
  generation: 1
  labels:
    operators.coreos.com/openshift-gitops-operator.openshift-operators: ""
  name: openshift-gitops
  namespace: openshift-operators
  resourceVersion: "935232"
  uid: 49a03851-70d0-4451-a01e-befea02fe0b9
spec:
  channel: latest
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operators.coreos.com/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"name":"openshift-pipelines","namespace":"openshift-operators"},"spec":{"channel":"latest","name":"openshift-pipelines-operator-rh","source":"redhat-operators","sourceNamespace":"openshift-marketplace"}}
  creationTimestamp: "2023-10-20T20:22:27Z"
  generation: 1
  labels:
    operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators: ""
  name: openshift-pipelines
  namespace: openshift-operators
  resourceVersion: "935242"
  uid: 119c2843-1cb5-4362-a169-f78266e55557
spec:
  channel: latest
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operators.coreos.com/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"name":"openshift-serverless","namespace":"openshift-operators"},"spec":{"channel":"stable","name":"serverless-operator","source":"redhat-operators","sourceNamespace":"openshift-marketplace"}}
  creationTimestamp: "2023-10-20T20:22:27Z"
  generation: 1
  labels:
    operators.coreos.com/serverless-operator.openshift-operators: ""
  name: openshift-serverless
  namespace: openshift-operators
  resourceVersion: "935248"
  uid: fa642d1f-1cc5-484a-bec2-6d45192874ad
spec:
  channel: stable
  name: serverless-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operators.coreos.com/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"name":"strimzi-kafka-operator","namespace":"openshift-operators"},"spec":{"channel":"stable","installPlanApproval":"Automatic","name":"strimzi-kafka-operator","source":"community-operators","sourceNamespace":"openshift-marketplace"}}
  creationTimestamp: "2023-10-20T20:22:27Z"
  generation: 1
  labels:
    operators.coreos.com/strimzi-kafka-operator.openshift-operators: ""
  name: strimzi-kafka-operator
  namespace: openshift-operators
  resourceVersion: "935224"
  uid: 74aefe53-5e95-417d-afce-c88ec061ed32
spec:
  channel: stable
  installPlanApproval: Automatic
  name: strimzi-kafka-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    olm.generated-by: install-gbx8d
  creationTimestamp: "2023-10-22T05:27:30Z"
  generation: 1
  labels:
    operators.coreos.com/mcg-operator.openshift-storage: ""
  name: mcg-operator-stable-4.11-redhat-operators-openshift-marketplace
  namespace: openshift-storage
  ownerReferences:
  apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Subscription
    name: odf-operator
    uid: b4c35cf6-203d-477a-95dc-5aad6d554add
  resourceVersion: "912430"
  uid: 814b2e57-8d18-477a-a279-a30c66caea16
spec:
  channel: stable-4.11
  installPlanApproval: Automatic
  name: mcg-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: mcg-operator.v4.11.11
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    olm.generated-by: install-gbx8d
  creationTimestamp: "2023-10-22T05:27:30Z"
  generation: 1
  labels:
    operators.coreos.com/ocs-operator.openshift-storage: ""
  name: ocs-operator-stable-4.11-redhat-operators-openshift-marketplace
  namespace: openshift-storage
  ownerReferences:
  apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Subscription
    name: odf-operator
    uid: b4c35cf6-203d-477a-95dc-5aad6d554add
  resourceVersion: "912453"
  uid: 1d503186-856d-4e10-92fc-b6e76034236a
spec:
  channel: stable-4.11
  installPlanApproval: Automatic
  name: ocs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: ocs-operator.v4.11.11
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    olm.generated-by: install-gbx8d
  creationTimestamp: "2023-10-22T05:27:30Z"
  generation: 2
  labels:
    operators.coreos.com/odf-csi-addons-operator.openshift-storage: ""
  name: odf-csi-addons-operator-stable-4.11-redhat-operators-openshift-marketplace
  namespace: openshift-storage
  ownerReferences:
  apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Subscription
    name: odf-operator
    uid: b4c35cf6-203d-477a-95dc-5aad6d554add
  resourceVersion: "912419"
  uid: 67f25582-073f-491e-aaef-56fd78f88343
spec:
  channel: stable-4.11
  config:
    tolerations:
    effect: NoSchedule
      key: node.ocs.openshift.io/storage
      operator: Equal
      value: "true"
  installPlanApproval: Automatic
  name: odf-csi-addons-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: odf-csi-addons-operator.v4.11.11
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: "2023-10-22T05:26:37Z"
  generation: 1
  labels:
    operators.coreos.com/odf-operator.openshift-storage: ""
  name: odf-operator
  namespace: openshift-storage
  resourceVersion: "905681"
  uid: b4c35cf6-203d-477a-95dc-5aad6d554add
spec:
  channel: stable-4.11
  installPlanApproval: Automatic
  name: odf-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: odf-operator.v4.11.11

