---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/devspaces.openshift-operators: ""
  name: aqua-operator-certified
  namespace: openshift-gitops
spec:
  channel: "2022.4"
  installPlanApproval: Automatic
  name: aqua-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: aqua-operator.2022.4.348
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: crunchy-postgres-operator
  namespace: openshift-operators
spec:
  channel: v5
  name: crunchy-postgres-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/devspaces.openshift-operators: ""
  name: devspaces
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: devspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: devspacesoperator.v3.9.0
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/devworkspace-operator.openshift-operators: ""
  name: devworkspace-operator-fast-redhat-operators-openshift-marketplace
  namespace: openshift-operators
spec:
  channel: fast
  installPlanApproval: Automatic
  name: devworkspace-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: devworkspace-operator.v0.23.0
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/openshift-gitops-operator.openshift-operators: ""
  name: openshift-gitops
  namespace: openshift-operators
spec:
  channel: latest
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines
  namespace: openshift-operators
spec:
  channel: latest
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/serverless-operator.openshift-operators: ""
  name: openshift-serverless
  namespace: openshift-operators
spec:
  channel: stable
  name: serverless-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1
  labels:
    operators.coreos.com/strimzi-kafka-operator.openshift-operators: ""
  name: strimzi-kafka-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: strimzi-kafka-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mcg-operator-stable-4.11-redhat-operators-openshift-marketplace
  namespace: openshift-storage
spec:
  channel: stable-4.11
  installPlanApproval: Automatic
  name: mcg-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: mcg-operator.v4.11.11
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    olm.generated-by: install-gbx8d
  
  generation: 1
  labels:
    operators.coreos.com/ocs-operator.openshift-storage: ""
  name: ocs-operator-stable-4.11-redhat-operators-openshift-marketplace
  namespace: openshift-storage
spec:
  channel: stable-4.11
  installPlanApproval: Automatic
  name: ocs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: ocs-operator.v4.11.11
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-csi-addons-operator-stable-4.11-redhat-operators-openshift-marketplace
  namespace: openshift-storage
spec:
  channel: stable-4.11
  config:
    tolerations:
    effect: NoSchedule
      key: node.ocs.openshift.io/storage
      operator: Equal
      value: "true"
  installPlanApproval: Automatic
  name: odf-csi-addons-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: odf-csi-addons-operator.v4.11.11
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: openshift-storage
spec:
  channel: stable-4.11
  installPlanApproval: Automatic
  name: odf-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: odf-operator.v4.11.11

