
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-csi-addons-operator-stable-4.11-redhat-operators-openshift-marketplace
  namespace: openshift-storage
spec:
  channel: stable-4.11
  config:
    tolerations:
      effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
  installPlanApproval: Automatic
  name: odf-csi-addons-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: odf-csi-addons-operator.v4.11.11
