apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: admins
users:
  - admin
  - admin2
  - admin3
  - user01
  - user02
  - user03
  - user04
  - user05
  - user06
  - user07
  - user08
  - user09
  - user10
  - user11
  - user12
  - user13
  - user14
  - user15
  - user16  