apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    machine.openshift.io/GPU: '0'
    machine.openshift.io/memoryMb: '43008'
    machine.openshift.io/vCPU: '16'

  name: cluster-56kl4-79fn6-worker-eu-west-1b
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-56kl4-79fn6
spec:
  replicas: 2
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-56kl4-79fn6
      machine.openshift.io/cluster-api-machineset: cluster-56kl4-79fn6-worker-eu-west-1b
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-56kl4-79fn6
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-56kl4-79fn6-worker-eu-west-1b
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          userDataSecret:
            name: worker-user-data
          placement:
            availabilityZone: eu-west-1b
            region: eu-west-1
          credentialsSecret:
            name: aws-cloud-credentials
          instanceType: c5n.4xlarge
          metadata:
            creationTimestamp: null
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ''
                volumeSize: 100
                volumeType: gp2
          securityGroups:
            - filters:
                - name: 'tag:Name'
                  values:
                    - cluster-56kl4-79fn6-worker-sg
          kind: AWSMachineProviderConfig
          tags:
            - name: kubernetes.io/cluster/cluster-56kl4-79fn6
              value: owned
            - name: uuid
              value: 9f6b6d36-c94c-5634-8ecd-06a2aa6c4d68
            - name: Stack
              value: project ocp4-cluster-56kl4
            - name: env_type
              value: ocp4-cluster
            - name: guid
              value: 56kl4
            - name: owner
              value: unknown
            - name: platform
              value: labs
          deviceIndex: 0
          ami:
            id: ami-080d1b5ac12af223b
          subnet:
            filters:
              - name: 'tag:Name'
                values:
                  - cluster-56kl4-79fn6-private-eu-west-1b
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          iamInstanceProfile:
            id: cluster-56kl4-79fn6-worker-profile

