apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-config

secretGenerator:
  - name: htpass-secret
    options:
      disableNameSuffixHash: true
    files:
      - htpasswd

#patchesStrategicMerge:
# patches:
# - htpasswd-cr.yaml
resources:
- htpassword-cr2.yaml
- admin-rb.yaml
