apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- monitor-namespace.yaml
- monitor-operatorgroup.yaml
- github.com/redhat-cop/gitops-catalog/grafana-operator/overlays/user-app

# Patch in namespace for Argo CD that is managing this namespace
patches:
- patch: |-
    - op: add
      path: /spec/config/users
      value:
        default_theme: light
  target:
    kind: Grafana
    name: grafana

patchesJson6902:
- target:
    version: v1alpha1
    group: operators.coreos.com
    kind: Subscription
    name: grafana
  path: patch-grafana-channel.yaml
- target:
    version: v1alpha1
    group: integreatly.org
    kind: Grafana
    name: grafana
  path: patch-grafana-sar.yaml
- target:
    version: v1
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: cluster-monitoring-view
  path: patch-cluster-monitoring-view.yaml
