apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# first install console add/ons
  - console/dev-view.yaml
  - console/links.yaml

# install all operators
  - operators/gitops.yaml
  - operators/pipelines.yaml
  - operators/serverless.yaml
  - operators/strimzi.yaml
  - operators/crunchy.yaml
  - operators/aqua.yaml
  - operators/devspaces.yaml
  - operators/devworkspace-operator.yaml
  - operators/mcg-operator.yaml
  - operators/ocs-operator.yaml
  - operators/odf-csi-addons-operator.yaml
  - operators/odf-operator.yaml
  
# configure registry
  - registry/image-registry.yaml
  - registry/config.yaml
  - argocd-instance.yaml
  - namespace-spaces.yaml
  - echipseche.yaml

