apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: global-load-balancer-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: nvidia-gpu-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-compliance
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat
---
apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-operator
